### ISSUE TITLE
Update the 2.ServiceTracker_App to match crosspane doc https://crossplane.io/docs/v0.11/

### ISSUE THREAD

**Issue by szihai** [oam-dev/samples#38]
Current version of the installation needs some update:
a. The wording "Install either the local OAM addon following its instructions or install both Crossplane and remote OAM addon." sounds like a free choice. 
It should lay out the scenarios, such as " if you deploy locally use OAM_local".  
b. The links in the section "Infrastructure Operator: Install Crossplane"  point the 0.9 version not 0.11.
c. The current crossplane provider database secret is called "alibaba-rdspostgresql-conn" under namespace "crossplane-system". The sample still uses "trackerdbconn" under "default".

**Comment by wonderflow** [comment]
Yeah, would you like to send a PR to fix them?
