### ISSUE TITLE
migrate all demos to v1alpha2

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/samples#39]
OAM v1alpha2 has released,  some of demos have migrated and some are left.
We should migrate all of them to v1alpha2.

* [ ] Helloworld https://github.com/oam-dev/samples/issues/40
* [ ] BikeSharing360_MultiContainer_App #41 
* [ ] BikeSharing360_SingleContainer_App  https://github.com/oam-dev/samples/issues/42

**Comment by captainroy-hy** [comment]
I can start from Helloworld #40.

**Comment by My-pleasure** [comment]
I can start from BikeSharing360_SingleContainer_App #42
