### ISSUE TITLE
Rudr referenced in samples is deprecated and should be replaced by KubeVela

### ISSUE THREAD

**Issue by ezYakaEagle442** [oam-dev/samples#53]
All [samples test environment refer to Rudr](https://github.com/oam-dev/samples) which is deprecated and replaced in favor of [KubeVela ](https://kubevela.io).

Samples should be retested with KubeVela and docs updated accordingly.

**Comment by resouer** [comment]
Thank you! Yes this is in progress of KubeVela 1.0 release.

**Comment by wonderflow** [comment]
It's done, thanks
